[package]
name = "polars-project"
version = "0.1.0"
edition = "2021"

[dependencies]
polars = { version = "0.43.1", features = [
  "lazy",
  "describe",
  "dtype-datetime",
  "strings",
  "regex",
  "temporal",
] }
chrono = "0.4.38"
rand = "0.8.5"
